name = "chicagoamp"
compatibility_date = "2025-02-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next/export"

[vars]
# Disable Next.js telemetry during Cloudflare builds
NEXT_TELEMETRY_DISABLED = "1"
